### ISSUE TITLE
Comparator Support

### ISSUE THREAD

**Issue by Lordmau5** [Lordmau5/FFS-v1.X#1]
Comparator support on valves, should output redstone corresponding to amount of fluid in the tank.

**Comment by rchard2scout** [comment]
Woot! [My idea! :D](https://www.reddit.com/r/feedthebeast/comments/3d5boc/introducing_ffs_fancy_fluid_storage_a_simple/ct24gf6)

**Comment by maxpowa** [comment]
It was on my todo for a while too, just got lazy yesterday when I had time :P
