### ISSUE TITLE
Re-logging invalidates tank.

### ISSUE THREAD

**Issue by marcin212** [Lordmau5/FFS-v1.X#10]
Tank becomes invalid after logging out and back in to a server. (chunk unloading?)

**Comment by maxpowa** [comment]
This must have to do with the new sizing stuff that @Lordmau5 implemented.

**Comment by Lordmau5** [comment]
Can't reproduce in dev-environment - confirmed in non-dev-env.
Will check tomorrow.

**Comment by marcin212** [comment]
Try on SMP

**Comment by Lordmau5** [comment]
SMP should be the same, if even SSP doesn't work in a normal Minecraft instance :)

It's just acting differently in a dev-environment...

Could it have to do with CCC, @maxpowa ?

**Comment by maxpowa** [comment]
It's a possibility, I'll take a look too when I get home tonight.

**Comment by marcin212** [comment]
it works
