### ISSUE TITLE
Tank desync?

### ISSUE THREAD

**Issue by epilimic** [Lordmau5/FFS-v1.X#17]
FancyFluidStorage Version:
1.1.36 (and .37)

MinecraftForge Version:
10.13.4.1448 - 1.7.10

SSP or SMP? (Client or Server):
SSP

Crash Report (via. Pastebin):
n/a it isn't crashing

What happens / happened?:
Was in the process of moving over my mob essence from a railcraft tank into this when I forgot I couldn't use EIO conduits so as I was changing to BC pipes I accidentally broke a couple pieces of the tank and it no longer thinks its a tank.
http://i.imgur.com/cAVUD7k.png

Hopped in IRC and maxpowa had me update to 1.1.37 but the tank still showed as invalid.

I then rolled back to my last good save with the tank working and noticed that there are actually 2 chunks of it that aren't being sync'd with the rest.
As you can see with WAILA it shows correctly here: http://i.imgur.com/kZ1rDh7.png
But not on the piece in the chunk next to it: http://i.imgur.com/qy0F4fU.png
This also happens on the chunk next to this non-working one.

Would like to note that the tank still actively receives fluid even with it in this weird state.

How can we reproduce it?:
Build a giant tank and maybe it will do the same thing? All I've done so far was built the tank and have been filling it via tesseract onto a valve placed in the centermost block up on the top. My tank is 32x32x32 and the only config option I changed was I:maxSize=32 from the default of 13.

**Comment by Lordmau5** [comment]
Please try it with build 38.

**Comment by Lordmau5** [comment]
Fixed in 1.2 / Build 38+.
