### ISSUE TITLE
Fluid changing in tank.

### ISSUE THREAD

**Issue by Guardian9978** [Lordmau5/FFS-v1.X#18]
FancyFluidStorage Version:
1.2.39
MinecraftForge Version:
10.13.4.1492
SSP or SMP? (Client or Server):
SMP
Crash Report (via. Pastebin):
Not crashing.
What happens / happened?:
Sometime either when the chunk unloads or when the server restarts the fluid in the tank changes to another fluid.
How can we reproduce it?:
I'm storing Creosote Oil from Immersive Engineering in the tank and when I returned to look at it after a server restart the fluid was Blueslime from Tinkers Construct. The issue is I can't reliably reproduce it.

**Comment by Lordmau5** [comment]
I have a feeling this is because we use the Fluid-ID's instead of the actual names...
I am gonna work on a fix, that should as well be compatible with older tanks, so nothing breaks (old ones will then adjust to the new system).

**Comment by Lordmau5** [comment]
Should be fixed with 1.3.
If this bug still occurs in the future, please reopen this issue (or make a new one if you forget that it still exists :))
