### ISSUE TITLE
Tank doesn't form with EnderIO Quite Clear Glass

### ISSUE THREAD

**Issue by evilhamsterman** [Lordmau5/FFS-v1.X#19]
FancyFluidStorage Version: 1.2.39

MinecraftForge Version: 1448

SSP or SMP? (Client or Server): SSP

Crash Report (via. Pastebin):

What happens / happened?: Built a tank with cobblestone floor, roof and corners, and QCG for the walls. Put a valve in the side and right click to create a tank but nothing happens.

How can we reproduce it?: See above, I did this with FTB Infinity version 1.8.2 which I believe has the latest EnderIO

**Comment by Lordmau5** [comment]
This is due to the fact that EnderIO glass is a Tile Entity.
The tanks do not support any other tile entities except the valves.

However, I talked with tterrag about it, and he said, the glass renders fine without a tile entity.
So that's gonna be in a whitelist soon :)

**Comment by evilhamsterman** [comment]
I thought that might be the case.

**Comment by Lordmau5** [comment]
Gonna be in v1.3.3 :)
