### ISSUE TITLE
Too much liquid in tank when making it smaller

### ISSUE THREAD

**Issue by rchard2scout** [Lordmau5/FFS-v1.X#2]
- Make a tank.
- Fill it with enough liquid.
- Make it smaller, so that the amount of liquid should not fit. (Don't break the valve, rebuild smaller tank on the same side as the old tank)
- Re-form the tank.

There is now more liquid in the tank than should fit. Some screenshots:

![2015-07-13_23 24 49](https://cloud.githubusercontent.com/assets/4447610/8661258/b46a4912-29b6-11e5-9245-ff37d0b00879.png)
A large tank with >432 buckets
![2015-07-13_23 25 52](https://cloud.githubusercontent.com/assets/4447610/8661279/d35c6472-29b6-11e5-82f5-2a3a9459da0b.png)
The valve hasn't moved, only the tank behind it has been rebuild. Still >432 buckets.
![2015-07-13_23 26 05](https://cloud.githubusercontent.com/assets/4447610/8661304/f686d1d0-29b6-11e5-9418-e1bf01e84c16.png)
I can take buckets out... (I was in creative, so I don't know if I actually _got_ the water, but I guess I did.
![2015-07-13_23 26 15](https://cloud.githubusercontent.com/assets/4447610/8661319/05cc25f0-29b7-11e5-8c11-d6959e988344.png)
As soon as I try to put in another bucket, the fluid level goes back to the maximum allowed level.

I don't know what the desired behaviour would be here, (Not reforming the tank? Losing the liquid on reforming it?) but I do know this should probably not be it.
(note: clean instance with Forge 10.13.4.1490, CodeChickenCore 1.0.6.43, NEI 1.0.4.107, Waila 1.5.10, Java 1.8.0_31 64-bit)

**Comment by maxpowa** [comment]
Desired behavior is to have fluid cap off at maximum level, this is definitely a bug. When making a tank smaller any excess fluid should be destroyed.
