### ISSUE TITLE
Crash on placing Valve

### ISSUE THREAD

**Issue by Gazmer** [Lordmau5/FFS-v1.X#22]
FancyFluidStorage Version: 1.3.3.54
MinecraftForge Version: 10.13.4.1472
SSP
Crash Report: http://pastebin.com/XwQBdgFJ
What happens / happened?: Game will crash on placing a valve anywhere.
How can we reproduce it?: place a valve I guess
Other Information of note:
Crash report mentions Computer craft, is this a dependancy? I dont have it as I have OpenComputers
Optifine and Fps+ are in use

Just relized Forge is out of date. Going to test. (Test failure, Results to follow)

FancyFluidStorage Version: 1.3.3.54
MinecraftForge Version: 10.13.4.1492
SSP
Crash Report: http://pastebin.com/JvwVE5AT
What happens / happened?: Game will crash on placing a valve anywhere.
How can we reproduce it?: place a valve I guess
Other Information of note:
Crash report mentions Computer craft, is this a dependancy? I dont have it as I have OpenComputers
Optifine and Fps+ are in use

**Comment by Lordmau5** [comment]
Expect a fix in a couple of minutes... I derped...

**Comment by Lordmau5** [comment]
Please respond if this fixed it for you. (Build 55)

**Comment by Gazmer** [comment]
Sorry It took so long I'm kind of nocturnal. And it is working, Huzzah!
