### ISSUE TITLE
Crash right after forge Preinitilization event

### ISSUE THREAD

**Issue by Reignofmagic** [Lordmau5/FFS-v1.X#23]
Hello!

Looking forward to seeing this fixed, as I can't currently use FFS and... well it is fancy!

I get a crash from "com/lordmau5/ffs/tile/TileEntityValve"

Full crash report: http://pastebin.com/UBcEZk8B
(yes that is a lot of mods... don't judge me)

FancyFluidStorage Version: Fancy Fluid Storage-1.7.10-1.3.4.58.jar, and 57, 51

MinecraftForge Version: 1.7.10

SSP or SMP? (Client or Server): SSP

Crash Report (via. Pastebin):http://pastebin.com/UBcEZk8B

What happens / happened?: Crashes just after the Pre-init event stage

How can we reproduce it?: Not really sure, because it was working previously... (at least version 51, and 57 were until I added galacticraft, remain in motion, and more planets mod) I specifically remember you showing a video of the mod working with remain in motion.... so yeah

**Comment by Lordmau5** [comment]
Problem in DragonAPI doing some weird class-magic apparently.
https://github.com/Lordmau5/FFS/issues/7#issuecomment-121754159

Rename "Fancy Fluid Storage..." to e.g. "A-Fancy Fluid Storage" so it loads before the DragonAPI.

**Comment by Reignofmagic** [comment]
Oh, simple, thanks for the answer!

**Comment by Lordmau5** [comment]
Did this fix the issue?
Just to be sure, so I can close this ;)

**Comment by Reignofmagic** [comment]
Yes it did sorry I didn't make that clear in my previous response.

**Comment by Lordmau5** [comment]
It's alright :)
