### ISSUE TITLE
Funky textuers

### ISSUE THREAD

**Issue by NassiC** [Lordmau5/FFS-v1.X#25]
When having something in your tanks the textures get all messed up. :) It shifts around when ever you move your mouse, it seems like the bottom and top frame dont have the problem.
To me it looks like its because the fluid textures are just behind  the tank textures, maybe pulling the fluid textures back to only fill airblocks inside the tank, to me that would look better aswell. :)

FFS Version: 1.3.4.57
Forge: 10.13.4.1492

I do use optifine, so this might be the reason.
Optifne_1.7.10_HD_C1

![83cf0f9725](https://cloud.githubusercontent.com/assets/8850655/9561473/b82e4c96-4e47-11e5-9924-132f9e4f735a.jpg)

**Comment by NassiC** [comment]
This can be fixed with turning off Fast rendering in optifine.

**Comment by Lordmau5** [comment]
Going to pull up a vote for the rendering soon, then. 
Both will be an option, the user vote will decide what will be the default though. :)

**Comment by Lordmau5** [comment]
![Preview](https://i.lordmau5.com/1443359797-151.png)
Is this how you would expect it?

**Comment by NassiC** [comment]
Yes that is how i would make it, if it was up to me. :)
To me it feels more right. I think it looks awesome that way.

**Comment by Lordmau5** [comment]
I added it as a config option.
By default, it's having the old way.
If people want to change it, they can change it through the config :)
