### ISSUE TITLE
Mobs spawn in tank

### ISSUE THREAD

**Issue by NassiC** [Lordmau5/FFS-v1.X#26]
Mobs spawn in the tank, even with fluids inside it. 
I tried making a void world, here it was easy to get mobs spawning in a tank with water. 
I had mobs spawn in a tank with lava as well.

FFS Version: 1.3.4.57
Forge: 10.13.4.1492

![ed6273a13c](https://cloud.githubusercontent.com/assets/8850655/9561588/a3180b04-4e4b-11e5-8b39-c57896508a7d.jpg)

![ba80727725](https://cloud.githubusercontent.com/assets/8850655/9561594/f1812e88-4e4b-11e5-92ac-56a1aa60d5af.jpg)

![8f3dba018c](https://cloud.githubusercontent.com/assets/8850655/9561605/5b6b0990-4e4c-11e5-9394-bd9c348251b2.jpg)

**Comment by Lordmau5** [comment]
This definitely should not be. 
Having a look into it once I get home (which means, next week)

**Comment by Lordmau5** [comment]
![Spawns](https://i.lordmau5.com/1443360124-152.jpg)
Looks fine to me after I made some fixes :)

Literally just one function that was missing.

Pushing the fix soon!

**Comment by NassiC** [comment]
Sounds great. :+1:
