### ISSUE TITLE
Crash when trying to break a tank with water in it

### ISSUE THREAD

**Issue by PokeMaserJ** [Lordmau5/FFS-v1.X#29]
FFS Build 1.8.9-1.4.4.68
Forge 11.15.0.1701
SSP
http://paste.feed-the-beast.com/view/8c96dd60 Crash Log
I crashed when trying to break Minecraft Glass on a Tank
Build a tank, fill with Water, try to break it

**Comment by Drullkus** [comment]
[Internal screaming]

**Comment by Lordmau5** [comment]
Hey, quickly dropping in.

I can't fix this up until the 1st of February, since I'm going to be away.

Could you please try and see if you can reproduce it _every time_ with those mods and when breaking a water-tank?

**Comment by PokeMaserJ** [comment]
My BAD. Chisel is to blame even though I didn't place any Chisel blocks. xD
