### ISSUE TITLE
Server crash when player enters chunk with FFS tank

### ISSUE THREAD

**Issue by kwpugh** [Lordmau5/FFS-v1.X#31]
Crash report:  http://pastebin.com/raw/U5xTrhgb

Mod version:  Fancy Fluid Storage-1.8.9-1.4.5.69
Forge version:  forge-1.8.9-11.15.1.1726-universal

Player made a tank (3x5x7) with about 50% full of lava
Player left the chunk
Now, if any player enters chunk, server crashes (report above).

Let me know if you need anything else.

**Comment by Drullkus** [comment]
Aaand that's how you make a proper bug report! Thanks :)

It seems like some faulty is going on in null checking.

**Comment by Lordmau5** [comment]
No idea how this is caused, because that `updateBlockAndNeighbors` method shouldn't be called in the `setAutoOutput`method, especially not on load.

Should be fixed in the upcoming build :)
