### ISSUE TITLE
[1.8.9-1.4.5.4.80] NPE on chunk load.

### ISSUE THREAD

**Issue by MrGraphic** [Lordmau5/FFS-v1.X#34]
Forge .1735
SSP
[Crash log](https://gist.github.com/MrGraphic/e8ab29d27ba6110fb9b8)

So, I updated from 1.4.4 and got that NPE. Then removed valves and recreated tank in same configuration and got same NPE after restart. There are two valves and tank is located in multiple chunks ( two to be exact ). Size of the tank 5x8x5.

**Comment by Lordmau5** [comment]
Gotta reopen it since I'd like to know if it _actually_ fixes it...

**Comment by MrGraphic** [comment]
That was quick and... yeah, you reduced NPE from world to block :P hehe.
[Log](https://gist.github.com/MrGraphic/7814686f659ff834795f)
Tried only to load save.

**Comment by Lordmau5** [comment]
Mind dropping on our IRC channel? Would be faster to respond on there :)

**Comment by Lordmau5** [comment]
Nevermind.
Mind checking if the problem still persists with this version?
~snip~

**Comment by MrGraphic** [comment]
Sorry, can't connect to IRC right now ( rules ). But, I recreated tanks ( still in .81 ) after removing valves ( save editing ) and that fixed that last NPE - that usualy fixes this kind of issue after updates. Now I can load save without a problem.
I can revert and check the last file you posted if it works without tricks if you wish.

**Comment by Lordmau5** [comment]
I really wouldn't mind if you could, since it should actually fix it properly...
And don't worry, it's fine that you can't drop on IRC :)

**Comment by MrGraphic** [comment]
Ok, checked that last one and same NPE as the one with ticking block. And again - replacing valves fixes that. Of course can't reproduce with newly placed valves as they works.

**Comment by Lordmau5** [comment]
Derp, it's always fun if you look at the wrong methods, right?
Should be fixed in the upcoming 1.4.5.5 build on Curseforge.

**Comment by MrGraphic** [comment]
Hehe, it's all cool :D.
