### ISSUE TITLE
1.8.9-Crash called NoClassDefFoundError

### ISSUE THREAD

**Issue by WenXin20** [Lordmau5/FFS-v1.X#35]
Forge Version: Forge 11.15.1.1726
Client
Crash on game launch
Crash Report:
http://pastebin.com/QmYAD40M

**Comment by Lordmau5** [comment]
I know where the issue is, but sadly I can't take care of it up until I'm at home this evening :(
You gotta hold out on another ~8h and stick to the version before...

**Comment by WenXin20** [comment]
Ok, that's fine.

**Comment by WenXin20** [comment]
Newest version seems to have fixed it.
