### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by sweetsosweet** [Lordmau5/FFS-v1.X#36]
**FancyFluidStorage Version:**
1.8.9-1.4.5.6.83
**MinecraftForge Version:**
1726 (also crashed on 1735)
**SSP or SMP? (Client or Server):**
SSP
**Crash Report (via. Pastebin):**
[Report](http://pastebin.com/sMH8rzdW)
**What happens / happened?:**
Crash before game loaded
**How can we reproduce it?:**
Start Minecraft; possibly related to mods I'm using

**Comment by Serifina** [comment]
I got an identical crash. NoClassDefFoundError suggests there's a dependency, but I don't know what the dependency is.

**Comment by Lordmau5** [comment]
Same as #35, moving discussion over there.
