### ISSUE TITLE
Waila doesn't show thousands separator on empty tank

### ISSUE THREAD

**Issue by rchard2scout** [Lordmau5/FFS-v1.X#4]
When a tank is empty, the thousands separator (comma) doesn't show in Waila.

![2015-07-13_23 38 01](https://cloud.githubusercontent.com/assets/4447610/8661503/4e4e4ba4-29b8-11e5-8744-702ae546d42d.png)
Empty tank, without thousands separator.
![2015-07-13_23 38 05](https://cloud.githubusercontent.com/assets/4447610/8661504/50a0317e-29b8-11e5-93c2-f964bbaaa2b3.png)
Tank with liquid, with thousands separator.

**Comment by Lordmau5** [comment]
https://github.com/Lordmau5/FFS/commit/7a672468d9803f4b0444c069673ffe58dc5683ab

Fixed with this, forgot the "4" before I pressed enter... nice... :D
