### ISSUE TITLE
FPS dropping over time with very large tanks.

### ISSUE THREAD

**Issue by ItchyFlea** [Lordmau5/FFS-v1.X#40]
**FancyFluidStorage Version**: 1.4.5.7.91

**MinecraftForge Version**: 11.15.1.1746

**Client or Server?**: Both? I run this mod on my server and encountered it on there.

**Crash Report (via. [Pastebin](http://pastebin.com/))**: N/A

**What happens / happened?**:
I have a 10x10x11 (WxDxH) tank near my base. If I stay near my base for extended periods of time (30-60mins, maybe more. Haven't really paid attention to the length of time) my FPS starts to slowly drop from a stable 60. The lowest it has gotten was 15 before I disconnected then reconnected.
The disco/reco seems to fix the issue for a short period of time, as my FPS goes back up to a stable 60. Breaking the valve on the tank fixes the issue, meaning the tank was the cause of the FPS dropping over time.

**How can we reproduce it?**:
Build a large 10x10x11 tank near your base and wait for an hour or two. My tank was built entirely out of Stone Brick and Glass, and had just over 920,000mb worth of lava in it when I broke it.

**Comment by Lordmau5** [comment]
What blocks is your tank made out of, if I may ask?
As in, mind sharing some screenshots?

Also sorry for the late response to this...

**Comment by ItchyFlea** [comment]
Stone brick blocks and ordinary glass. Screenshot attached showing tank, currently missing it's valve.

I do have another, smaller tank underground. I have no issues with FPS dropping with that tank. The smaller tank is about half the size of this one. (IIRC 4x4x5 (WxDxH))

![2016-03-16_23 16 20](https://cloud.githubusercontent.com/assets/10439814/13808925/4a31570a-ebcd-11e5-891e-00f4a261d5c9.png)

**Comment by Lordmau5** [comment]
Strangely enough, I already get a bunch of framedrops with VSync activated from 60 down to 40, despite having a beefy computer (i7 6700, 16GB RAM, AMD R9 390X) WITHOUT having anything tank-related on the structure.
![Image1](https://i.lordmau5.com/1458124530-735.png)
![Image2](https://i.lordmau5.com/1458124576-737.png)

I really have no idea what else could cause this...
@Drullkus @maxpowa , any idea?

**Comment by Drullkus** [comment]
¯\_(ツ)_/¯

**Comment by Lordmau5** [comment]
#48 might be related...

@ItchyFlea Could you test it with the newest build again, perhaps?
I'm sorry that I'm late to the party, but I didn't really know where to look for a potential fix.
I think the newest build might actually fix this :P
