### ISSUE TITLE
Issue: fancy-fluid-storage-1.9-1.4.5.7 crashes dedicated forge server 1.9 build 1804 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lordmau5/FFS-v1.X#42]
**FancyFluidStorage Version**: 1.9-1.4.5.7 

**MinecraftForge Version**: 1.9 build 1804

**Client or Server?**:
- [ ] Client
- [X] Server

crash report:
https://gist.github.com/1f14e02fc8c72f2dd109

fml server latest:
https://gist.github.com/5810b1ba2ce35d327aeb

**What happens / happened?**:
Server crashed on startup

**How can we reproduce it?**:
Install this version on a dedicated server

**Comment by maxpowa** [comment]
_facepalm_ 

Well that was a mistake.
