### ISSUE TITLE
FFS{1.9-1.4.5.7} crashes dedicated forge server 1.9 build 1804 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lordmau5/FFS-v1.X#43]
**FancyFluidStorage Version**:
1.9-1.4.5.7

**MinecraftForge Version**:
1.9 build 1804

**Client or Server?**:
- [ ] Client
- [x] Server

crash report:
https://gist.github.com/d64378168d55243992ef

fml server latest:
https://gist.github.com/36331c50047d4a18c0dd

**What happens / happened?**:
Server crashes just like in the 1.8.9 version

**How can we reproduce it?**:
Install mod on server

**Comment by Lordmau5** [comment]
1.4.5.8 should fix this.
Just uploaded it to Curseforge, will take a bit to be verified.
Once it's available, please try it again and respond if it works :)

**Comment by kreezxil** [comment]
this part is fixed

However now the client crashes during play while I was near lava and when a creeper wanted to blow up on me.

fml log http://paste.ee/p/jAd0V

crash report: http://paste.ee/p/0KQ8y

**Comment by Lordmau5** [comment]
Please try it with 1.4.5.9, it's currently under review on the Curseforge project.

**Comment by kreezxil** [comment]
Issue: FFS{1.9-1.4.5.7} [Fancy Fluid Storage](fancy-fluid-storage-1.9-1.4.5.9.jar) which is really 1.4.5.9 but reports the wrong version internally crashes dedicated forge server 1.9 build 1809 on startup

crash report:
https://gist.github.com/4834339b5e0a98b50fa3

fml server latest:
https://gist.github.com/5afb9c3855526642d816

**Comment by Lordmau5** [comment]
Alright, apparently it was because we were building against a lower version of Forge.
Would you mind trying with the newest one, 1.5, again, please? :)

**Comment by kreezxil** [comment]
The 1.5 you have out is for 1.8.9. I've moved on to the 1.9. See the first entry in this stream. Thanks. :)

**Comment by Lordmau5** [comment]
Oh yea, I have to bring the changes over to 1.9. Give me ~1 hour or so. Didn't get to it yesterday :/

**Comment by Lordmau5** [comment]
Alright it's up - Please grab the 1.5.1 version for MC1.9 and check if that fixed it.
