### ISSUE TITLE
Crashing while Gaming

### ISSUE THREAD

**Issue by Noritus** [Lordmau5/FFS-v1.X#45]
FancyFluidStorage 1.4.5

MinecraftForge 1.8.9 - 11.15.1.1808

Client

Crash Report (via. [Pastebin](http://pastebin.com/vThcFVd9))

**Comment by Lordmau5** [comment]
Same as #43 .
Please try it with 1.4.5.9, it's currently under review on the Curseforge project.
For further discussion, please check into issue #43.
