### ISSUE TITLE
ClassNotFound Crash

### ISSUE THREAD

**Issue by Lanse505** [Lordmau5/FFS-v1.X#46]
**FancyFluidStorage Version**:
1.4.5.8
**MinecraftForge Version**:
1.9-12.16.0.1809-1.9
**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://puu.sh/nThSh/4da290856c.txt

**What happens / happened?**:
Crash on Load-Up

**How can we reproduce it?**:
All I did was try to boot up the small 1.9 private pack i'm building.

**Comment by Lordmau5** [comment]
Please try it with 1.4.5.9, it's currently under review on the Curseforge project.

**Comment by Lanse505** [comment]
will do ^^

**Comment by Lanse505** [comment]
Tested against 1.4.5.9:
http://puu.sh/nTlES/05045c5cfa.txt

**Comment by Lordmau5** [comment]
What the hell, man... this is weird...
Mind dropping on our IRC on Esper real quick?
Chanel is _#FFS_.
Would be better to quickly talk over there

**Comment by Lanse505** [comment]
disregard o.o i might have derped?

**Comment by Lanse505** [comment]
need to do some checking on my side first ^^ then i'll jump on IRC

**Comment by Lanse505** [comment]
Yup
http://puu.sh/nTlES/05045c5cfa.txt

Will jump on FFS now

**Comment by Lanse505** [comment]
I'm in #FFS now if you have any more questions

**Comment by Lordmau5** [comment]
Actually, let's reopen this.
I wanna get a certain @TheCricket into this discussion o/

**Comment by Lordmau5** [comment]
Closing down. No response, so I'll just take this as dead again ;)
If another crash with said mod happens, I'll make sure to try and contact him again though.

**Comment by Drullkus** [comment]
For any future users looking at this issue, please use [Chisel](http://minecraft.curseforge.com/projects/chisel), not Chisel-3. Chisel-3 was being developed by a different user but that user has since dropped use.

@Lanse505 :P
