### ISSUE TITLE
1.9-1.5.1 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lordmau5/FFS-v1.X#47]
Issue: fancy-fluid-storage-1.9-1.5.1 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/b3028722f74f818565966812ed8b45fb

fml server latest:
https://gist.github.com/1718502fc471a35f9d1f43fc10714963

**Comment by Lanse505** [comment]
I get this crash too on any build above 1821

**Comment by Lordmau5** [comment]
Fixed in 1.5.1.1
http://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage/files/2292159
