### ISSUE TITLE
Crashes when adding an Pressure Pipes Output in front of the Valve.

### ISSUE THREAD

**Issue by gr4y** [Lordmau5/FFS-v1.X#49]
**FancyFluidStorage Version**: 1.8.9-1.5.1.97

**MinecraftForge Version**: 1.8.9 - 11.15.1.1808

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/ANGCAn6m

**What happens / happened?**:

The game crashed and doesn't load anymore. 

**How can we reproduce it?**:

Create a tank with 3x3x3 (inner diameter) out of IC2 Construction Foam Walls (painted light blue) and light blue stained glass, one valve and one ffs computer, then place an Pressure Output (from Pressure Pipes by @bdew) in front of the Valve, the game crashes and doesn't even load anymore. 

Anyway, I want to thank you for this really awesome mod! :+1: :grin:

**Comment by Lordmau5** [comment]
Bit late to responding to this, but this should be fixed in the newest build - mind testing again?
