### ISSUE TITLE
FFS Causes server crash during startup

### ISSUE THREAD

**Issue by NonniGB** [Lordmau5/FFS-v1.X#5]
Running a slightly modified FTB Infinity. Added FFS to my local server and client. The client loads up just fine, but the server doesn't like it. Seems to be some sort of conflict with Extra Utilities, perhaps?

Crash log:
http://pastebin.com/BEgg21Ju

Thanks for making this, looks awesome :)

**Comment by maxpowa** [comment]
Hmm, I think I know what's causing that. I'll look into it in a couple hours.

**Comment by maxpowa** [comment]
Fixed by 5cc929d. Please try updating to the latest version from Jenkins, Curseforge is awaiting approval.
