### ISSUE TITLE
Tanks to use multiple solid blocks.

### ISSUE THREAD

**Issue by Drullkus** [Lordmau5/FFS-v1.X#51]
Why? [No good reason.](https://cloud.githubusercontent.com/assets/5010174/15447107/5603628a-1eea-11e6-8378-c5f589994d3f.png)

**Comment by Lordmau5** [comment]
I love that you, as **our** texture artist, part of the developer team, **can't look into the config file**.

https://github.com/Lordmau5/FFS/blob/master/src/main/java/com/lordmau5/ffs/FancyFluidStorage.java#L103-L110
