### ISSUE TITLE
Server crash after creating a tank

### ISSUE THREAD

**Issue by MrJoki007** [Lordmau5/FFS-v1.X#52]
**FancyFluidStorage Version**: Fancy Fluid Storage-1.8.9-1.5.2.7.jar

**MinecraftForge Version**: forge-1.8.9-11.15.1.1890-1.8.9-universal.jar

**Client or Server?**: Server
- [ ] Client 
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://hastebin.com/eqeciloheh.coffee

**What happens / happened?**: I just created a tank and right clicked the valve and then the server crashed and now when it starts it crashes again

**How can we reproduce it?**: Maybe use Stoneburnt as frame and Thickend Glass as glass

**Comment by Lordmau5** [comment]
Please try it with the newest alpha build for 1.8.9 and report again so I can potentially push that to a release build :P

**Comment by MrJoki007** [comment]
That fixed it thx :D
