### ISSUE TITLE
1.9-1.5.1.1.2 crashes dedicated forge server 1.9.4 build 12.16.1.1923 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lordmau5/FFS-v1.X#53]
**FancyFluidStorage Version**: 1.9-1.5.1.1.2

**MinecraftForge Version**: 12.16.1.1923

**Client or Server?**:
- [ ] Client
- [x ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: https://gist.github.com/6f110a30844fda6042b609f9a2ef3f92

**What happens / happened?**:
crashed on startup

**How can we reproduce it?**:
Use this version of Forge --> 12.16.1.1923 

fml server latest:
https://gist.github.com/bc484c08374e1f6f304c3cb137402fdc

**Comment by Lordmau5** [comment]
_Sad look_
The only thing I can suggest is that you try it with 1.5.1.2.3 (the last 1.9 build) 

Other than that, there's not much I can do. 
I'm not working on 1.9 anymore - 1.9.4 is where it's at, sorry
