### ISSUE TITLE
Server automatically stops after starting

### ISSUE THREAD

**Issue by MrJoki007** [Lordmau5/FFS-v1.X#56]
**FancyFluidStorage Version**: 1.5.2.9

**MinecraftForge Version**: 1890

**Client or Server?**:
- [x] Server
- [ ] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**: [FML]: The mod FFS has attempted to allocate a chunkloading ticket beyond it's currently allocated maximum : 200

**What happens / happened?**: I chunkloaded my base with FTB Utilities and then i restarted my server and now it doesnt start anymore

**How can we reproduce it?**:

**Comment by Lordmau5** [comment]
Which MC version are you on?

**Comment by Lordmau5** [comment]
Should be fixed in 1.5.3.10 (for 1.8.9) and 1.5.6 (for 1.9.4).
Would love if you could report on being able to get into the world again :)

**Comment by MrJoki007** [comment]
Thx it's 1.8.9

**Comment by Lordmau5** [comment]
File is approved, go have a check, please.
http://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage/files/2305176

**Comment by MrJoki007** [comment]
Yeah im testing it right now

**Comment by MrJoki007** [comment]
But its not fixed in the new version :(

**Comment by Lordmau5** [comment]
what's the issue now?
Still the same?

**Comment by MrJoki007** [comment]
Yes im getting the same error

**Comment by Lordmau5** [comment]
Can you drop me a full crash log on pastebin?

**Comment by MrJoki007** [comment]
The server only stops and doesnt crash and you cant see the message in the fml-server-latest.log and this one is to large for pastebin

**Comment by Lordmau5** [comment]
Dropbox or similar?

**Comment by MrJoki007** [comment]
https://www.dropbox.com/s/cae9pfyhlbubig3/fml-server-latest.log?dl=0
