### ISSUE TITLE
Server startup crash

### ISSUE THREAD

**Issue by cauliflower69** [Lordmau5/FFS-v1.X#58]
**FancyFluidStorage Version**: 1.9.4-1.6.0-b19

**MinecraftForge Version**: Forge 12.17.0.1954

**Client or Server?**:
- [ ] Client
- [x ] Server

**Crash Report http://pastebin.com/ibfQSwRc

**What happens / happened?**: Server crashes on startup

**How can we reproduce it?**: Try launching with server

**Comment by maxpowa** [comment]
Duplicate of #55

**Comment by Lordmau5** [comment]
`FarseekCoreMod (Farseek-1.9.4-1.0.jar)`

Check #55, not our fault, sorry.

**Comment by cauliflower69** [comment]
Thanks
