### ISSUE TITLE
Sides of fluid in tank displays in 32x resolution, while top of fluid displays as 16x

### ISSUE THREAD

**Issue by BBoldt** [Lordmau5/FFS-v1.X#6]
![](http://i.imgur.com/NfrQkq9.png)

As a texture artist, this hurts my soul. :stuck_out_tongue_closed_eyes:

**Comment by maxpowa** [comment]
AFAIK, this is intended behavior. @Lordmau5 can you please comment on this?

**Comment by Lordmau5** [comment]
This is indeed not intended.

Small downbreak of why this happens:
- We use the stationary texture of the fluid on the top
- We use the moving texture of the fluid on the sides
- The stationary texture is apparently 16x16
- The moving texture is apparently 32x32
- A hotfix would be to set the moving "MaxU" and "MaxV" corresponding to "MinU + (stationary U difference)" and "MinV + (stationary V difference)".

This would look like this:
![image](http://ss.lordmau5.com/2015-07-15_12-12-11.png)

Personally, I prefer this hotfix.
I will do a commit in a few minutes :)

**Comment by BBoldt** [comment]
Awesome!

It looks great with the sides matching the resolution.

**Comment by Lordmau5** [comment]
Since @maxpowa 's Jenkins is currently down (and therefore, uploading to Curseforge), I could drop you a custom build if you really want one.
Just a heads up :D

**Comment by BBoldt** [comment]
not really necessary, I'll be asleep before I have a chance to test it out

Thanks for the offer though :D
