### ISSUE TITLE
[1.8.9] Multiple Issues, Possible Incompatibility with Immersive Engineering?

### ISSUE THREAD

**Issue by Phonavis** [Lordmau5/FFS-v1.X#61]
**FancyFluidStorage Version**: 1.5.3.11

**MinecraftForge Version**: 11.15.1.902

**Client or Server?**:
- [X ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
None
**What happens / happened?**:
Well uh, this is gonna be pretty hard to explain. Basically, I right clicked the valve and created a tank about 5 blocks to the right of my IE Coke oven. The coke oven ended up turning the same size as the tank, and glitched the rendering on nearby blocks causing flashing of said coke oven. Relogging into teh server, fixed it, and the tank was formed fine. Destroying a block of the tank didn't fix the coke oven, so you have to relog no matter what. Then someone suggested it might be my resource pack, so after changing back to default from JSTR (I don't get how it could be the resource pack's issue, it's rendering) I broke a block of the tank again, while the render issue was still happening. This ended up destroying all of the blocks except the valve of the tank, for... Reasons.
Rendering issue
![Image1](http://puu.sh/pvtO4/76f567350e.jpg)
Entire tank now gone after breaking block
![Image2](http://puu.sh/pvule/697f90d0ed.png)
**How can we reproduce it?**:
well, the procedure I listed

**Comment by Lordmau5** [comment]
Are you using Optifine in combination with the fast-render option by any chance?
Or Optifine at all (that might be the first thing to ask for, haha)

**Comment by Phonavis** [comment]
Nope no Optifine..
