### ISSUE TITLE
Crash on startup!

### ISSUE THREAD

**Issue by KristjanKr** [Lordmau5/FFS-v1.X#63]
**FancyFluidStorage Version**:FFS v1.6.2-b21

**MinecraftForge Version**:1968

**Client or Server?**:
- [x ] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:http://paste.ee/p/HSj1W (estonian pastebin)

**What happens / happened?**: Crashes on startup with crashlog mentioned before

**How can we reproduce it?**:
Get Chisel3 initial release from: http://minecraft.curseforge.com/projects/chisel-3-the-cricket-strikes-back/files (Chisel3.0.jar)
Get latest FFS as right now.
Put these mods together and have a crash.

**Comment by Lordmau5** [comment]
Use the newest version and tell me what the crash log is on that one, thank you.
