### ISSUE TITLE
[1.9.4] Crash on startup - Wrongly detected Chisel

### ISSUE THREAD

**Issue by MrAmericanMike** [Lordmau5/FFS-v1.X#64]
**FancyFluidStorage Version**: 1.9.4-1.6.3-b22

**MinecraftForge Version**: 1.9.4-12.17.0.1968

**Client or Server?**:
- [ ] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://pastebin.com/K5aR3Abk

**What happens / happened?**:
Pack crash on launch

**How can we reproduce it?**:
Not sure.

**Comment by MrAmericanMike** [comment]
PS: It doesn't happens using Fancy Fluid Storage-1.9.4-1.6.2-b21

PS2: What's wrong with Chisel 3? You sending on a 1.9.4 Mod to check for Chisel on http://minecraft.curseforge.com/projects/chisel when there is no Chisel 1.9.4 there, and the ones on their DEV site, is that, a DEV version that still full of bugs.

**Comment by blockbreaker1361** [comment]
I'm getting the same crash. http://pastebin.com/JGxLeAQW
I took Chisel out and it still tells me that Chisel is still installed.

**Comment by Lordmau5** [comment]
Go for 1.6.2 for now, I'm currently working on a fix.
Apparently I mixed up the logic on the check and am working on it as we speak.

**Comment by Lordmau5** [comment]
Okay, could you please try it with the newest build?
https://jenkins.maxpowa.us/job/FFS/branch/1.9/

**Comment by MrAmericanMike** [comment]
b23 works now.

PS: Do you think it's a good idea to Crash a pack, just because other mod was detected? A warning message would be better alternative for this. 
At the end Chisel 3 and FFS could both be on the same pack without problem. People just need to be aware of not using Chisel 3 blocks on FFS setups.

**Comment by Lordmau5** [comment]
Chisel 3 should not be used because I'm not supporting a mod that is being made through a fucking shitstorm.

And it's way deeper than that because Chisel 3 is crashing **MY MOD**.

Please read through #62 , because I explain it in there :)
