### ISSUE TITLE
crash with Chisel 3

### ISSUE THREAD

**Issue by 0Navis0** [Lordmau5/FFS-v1.X#65]
I create an issue like it has been asked to me.
http://pastebin.com/ZthAEuDS

**Comment by Lordmau5** [comment]
It appears you're not using the latest version :/

As said already, please use the latest and see what the crash on that is.

**Comment by BootyToast** [comment]
I'm having the same issue with the latest version.

Crash report: http://pastebin.com/3kRh3hSv

**Comment by Lordmau5** [comment]
Compared to him, you are at least running the **latest** version ;)

Paying a closer look towards the crash log reveals the following:

_`java.lang.Exception: You are using an unsupported version of Chisel, which crashes my mod when being used.
Please use the proper, supported version from one of the following links:
http://minecraft.curseforge.com/projects/chisel
http://ci.tterrag.com/job/Chisel/branch/1.9%252Fdev/`_

Which concludes that this will be marked with the following label as well and therefore be closed.

**Comment by 0Navis0** [comment]
Why can you not add a support for this version ?

**Comment by Lordmau5** [comment]
As posted here:
https://github.com/Lordmau5/FFS/issues/62#issuecomment-226989529

_Long story short:
Chisel 3 is not supported and the @Optional field is not kicking in properly.
Both mods, Chisel 3 and Chisel-Team's Chisel use the same modid, so the Optional field is useless._

Also because I don't want to support a mod being made by someone with a ego bigger than the entire solar system.

**Comment by 0Navis0** [comment]
Lol, you are pretty hard with him. XD
So for summarizing, you make crash your own mod only because you don't want to support this Chisel version.

**Comment by Selim042** [comment]
From what I understand, it is extremely difficult to determine the difference between Chisel 3 and Chisel-Team's Chisel due to the fact that they have the same modid.  That means if anything needs to get handled differently between the two Chisels, FFS cannot determine the difference and what operation to use.

**Comment by Lordmau5** [comment]
@Hypsellis Cricket would need to change the modid of his version. And he's too stubborn to do that, sadly.

//EDIT:
@Selim042 Exactly. If Forge would have a optional version parameter for the @Optional annotation, then I could get some decent compatibility out of this. But well, that's not the case.

//EDIT2:
Also, I'm being hard on him from all the shitstorming that's been going around prior to this **RECURRING** crash.

Chatlog from one developer channel on Esper:
http://pastebin.com/zKA0nDPP

**Comment by 0Navis0** [comment]
Wow so much drama for my issue, damn I didn't think it would go so far. @____@'

**Comment by Lordmau5** [comment]
It's not _your_ issue. It's a general issue with those 2 mods and I'm sorry you feel like being part of it.

Don't worry, you're not involved in this, it's just the Chisel-Team, Cricket and me basically. ;)

**Comment by 0Navis0** [comment]
It's fine, I understand better now what happens, sorry to have said that you were immature and stupid, it's him who is in fact.

**Comment by TheCricket** [comment]
You can actually support both! @Vexatos actually has a way in his code here http://git.io/voapc which all you have to do is Mods.hasVersion("chisel", "(,3)") for their chisel and Mods.hasVersion("chisel", "[3,)") for my chisel

https://www.youtube.com/watch?v=uVjRe8QXFHY

**Comment by Vexatos** [comment]
@TheCricket You cannot use `@Optional` though.

**Comment by BootyToast** [comment]
Thank you, @Lordmau5 
Drullkus has said a proper release is coming very soon so I will hold out for that :D

**Comment by TheCricket** [comment]
Correct Vexatos, I never said you could :P and absolutely no reason to BootyToast

**Comment by Lordmau5** [comment]
> Correct Vexatos, I never said you could :P

I don't get why you offered it to me then, doesn't make sense... but okay...

> and absolutely no reason to BootyToast

Hmm? He can use the version he wants to use, to be honest.

**Comment by Lordmau5** [comment]
From what I've heard you're stopping on your Chisel again?

I'm not _that_ frustrated to hear that because that'll stop the compatibility issues.

Gotta close this now then
