### ISSUE TITLE
Environmental Tech compatibility

### ISSUE THREAD

**Issue by ghost** [Lordmau5/FFS-v1.X#66]
**FancyFluidStorage Version**: FFS v1.6.4-b28

**MinecraftForge Version**: forge-12.18.1.2014

**Client or Server?**: Client

**Crash Report**:
http://pastebin.com/U0kd9arw

**What happens / happened?**:
Created a 5x5x5 tank using iron blocks and Clear Glass from Environmental Tech, attached the valve, right clicked it and it crashed. After this I tried to enter the same world again but it`s corrupted, it crashes on loading.
Is there a way to manually add mod added blocks into ffs`s "whitelist" ?

**Comment by Lordmau5** [comment]
I'm not able to fix this nor look at it up until ~1st of August due to being on vacation :/

Newest code is up though. If anyone wants to take a crack at it, please do!
