### ISSUE TITLE
Ticking block entity Crash

### ISSUE THREAD

**Issue by goldern** [Lordmau5/FFS-v1.X#67]
**FancyFluidStorage Version**: 1.7.10-1.3.7

**MinecraftForge Version**: 7.10.99.99

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/PnQhpv2x

**What happens / happened?**: After setting up a lava pump at nether, crashes.

**How can we reproduce it?**: Dumping lava from a tesseract into a Fancy Tank

**Comment by phantamanta44** [comment]
Out of curiosity, how large was your tank?

**Comment by Lordmau5** [comment]
1.7.10 is completely unsupported, sorry.

**Comment by goldern** [comment]
7x7x7, 5x5x5 interior
