### ISSUE TITLE
Breaking tank value eats entire tank

### ISSUE THREAD

**Issue by ShadowDrakken** [Lordmau5/FFS-v1.X#71]
**FancyFluidStorage Version**: 1.6.4b28

**MinecraftForge Version**: MC 1.10.2 - Forge 2046

**Client or Server?**:
- [X] Client
- [X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
n/a

**What happens / happened?**:
When breaking a tank value, all the blocks that make up the tank vanish as well.

**How can we reproduce it?**:
Break a tank value with a valid, functioning tank

**Comment by Lordmau5** [comment]
Please refer to the issue template as those that are not done with it are invalid.

**Comment by ShadowDrakken** [comment]
There
