### ISSUE TITLE
Tinker's Construct clear glass crash

### ISSUE THREAD

**Issue by WillCon** [Lordmau5/FFS-v1.X#82]
**FancyFluidStorage Version**:1.10.2-1.6.328

**MinecraftForge Version**:12.18.2.2125

**Client or Server?**:
- [ I don't know how to check these, but I was in a single player world] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:http://pastebin.com/k61aM9cm

**What happens / happened?**:When trying to make a tank using Tinker's Construct's "clear glass" the game crashes. (Also blocks with connected textures turn invisible when you make a tank w/ them)

**How can we reproduce it?**:Download Tinker's Construct, try to make a tank with the clear glass (and then try and use anything with connected textures, like the glass from Chisel, which I really want to use in a tank, this doesn't cause a crash it just doesn't show up and so it's not as fancy)

**Comment by Lordmau5** [comment]
Stamp reporting issues, please wait till I have v2.0 ready and those will all go away :(

**Comment by Lordmau5** [comment]
Stawp*
