### ISSUE TITLE
Multiple buckets in hand won't fill

### ISSUE THREAD

**Issue by RDecker** [Lordmau5/FFS-v1.X#84]
**FancyFluidStorage Version**:
1.10.2

**MinecraftForge Version**:
12.18.3.2185

**Client or Server?**:
- [ ] Client
- [ ] Server
Neither, LAN

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
Did not cause a crash.

**What happens / happened?**:
With multiple buckets in the character's hand, fluid was being removed from the tank, but not producing a bucket filled with (in this case) lava.

**How can we reproduce it?**:
We built this tank set up and tried to extract with 3 buckets in hand. Liquid level went down, but we did not get Lava Bucket in our inventory.
Using single buckets did work.
![2017-02-25_21 24 38](https://cloud.githubusercontent.com/assets/4666964/23337402/419f862c-fba1-11e6-9a03-7b456a183e33.png)

**Comment by Lordmau5** [comment]
1.X is deprecated and not being fixed / updated anymore, sorry.
