### ISSUE TITLE
Sorry for using this repository, but do you still have your old 1.2.5 MCPC ports?

### ISSUE THREAD

**Issue by ghost** [Lordmau5/FFS-v1.X#86]
So, I'm really sorry for using your repository, but I don't know other ways to contact you. Do you still happen to have your old 1.2.5 MCPC ports (listed below; all of the files are for MC 1.2.5)?

More Tools 'n' Such 1.2.5
More Stackables 1.2.5
Generate Nether Ores 1.1
Crafting Table III (B1.2 ~ B1.8)
Secret Rooms Mod 4.0.0/1
Nether Ores 1.2.1

Do you also have the clients for these mods? I'm trying to archive all of those legacy mods with the help of a few people at the MC Archive. Since information about the old mcportcentral forums are so scarce nowadays, it's really hard to learn how to make reliable MCPC+ ports again.

Either way, thank you.

**Comment by Lordmau5** [comment]
My god you just sent me down an immense rabbit hole for trying to track these down...

However - I was able to find everything except Secret Rooms Mod (I do have some source for a mod called `Hidden Doors` though...)

See if some of this stuff is in any way helpful to your project.

If you've got more questions, please reach out through Discord though, as using GitHub for a quick discussion is... urgh... horrible to put it nicely.

`Lordmau5#0001`

[OldMods.zip](https://github.com/Lordmau5/FFS-v1.X/files/5583882/OldMods.zip)

**Comment by ghost** [comment]
Sure thing, I'm glad you still had it all! Thank you for your help.

**Comment by Lordmau5** [comment]
I do assume this is resolved then now? Again, if there's more you'd like me to look for or something similar, the Discord ID is up there :)

I'mma close this issue in that case
