### ISSUE TITLE
Auto-output invalidates tank.

### ISSUE THREAD

**Issue by marcin212** [Lordmau5/FFS-v1.X#9]
When I use the auto-output toggle in the valve GUI, the tank becomes invalid.

**Comment by Kubuxu** [comment]
Still doesn't work in build 30.

**Comment by marcin212** [comment]
Still doesn't work in build 33

**Comment by Kubuxu** [comment]
@marcin212 in weird way it started to work for me after few restarts on SSP.

**Comment by marcin212** [comment]
https://www.youtube.com/watch?v=IU1qO-J9uJ4&feature=youtu.be

**Comment by marcin212** [comment]
it works
